### ISSUE TITLE
Removing the infinite loop guard in the bootsector does not prevent qemu from executing it

### ISSUE THREAD

**Issue by lebel-louisjacob** [cfenollosa/os-tutorial#102]
## Context
There is a behaviour (maybe) related to qemu I don't understand.

I just tried the [first lesson](https://github.com/cfenollosa/os-tutorial/tree/master/01-bootsector-barebones), and I wanted to see what would happen to the V.M. if the infinite loop "guard" was removed.

#### Note:
`bootsector.asm`:
```nasm
jmp $ ; <--<--<--<--<-- the infinite loop i'm talking about
times 510-($-$$) db 0
dw 0xaa55
```

## Expected
Qemu crashes.

## Actual
Nothing changes visually. No error or warning is issued.

## Issue
I don't understand what happens behind the scene. Is the presence of an infinite loop at the end of a boot-sector optional? Or is qemu some sort of wizard that knows magically when to stop the execution of the boot-sector?

**Comment by Teln0** [comment]
Ive noticed that nasm reacts weirdly to errors, by just "loading the back up of the previous version". I dont know if thats true, just a feeling

**Comment by jlagarespo** [comment]
QEMU would just continue running whatever there is in memory after the bootsector. Which is zeros. Or garbage data. Once it has gone over all the zeroes of the bootsect it finds the magic number. Let's dissasemble the magic number. What does it do?
```x86asm
push bp
stosb
```
and so we push bp to the stack and issue the stosb instruction(which by having SI and DI undefined, we are not sure what is it doing). Then we continue running. Likely we find more zeroes. Or maybe BIOS code all over the place. The behaviour is undefined. Probably just running up in memory forever.
Why would any warning or error be issued by QEMU?
As you yourself said, QEMU is not a wizard that knows where the bootsector stops, so how could it know when(or why) to throw a warning?
It just runs what is in memory. Simple enough, that's how computers work.

Hope that awnsered your question :)

**Comment by lebel-louisjacob** [comment]
Simple and clear. Thanks!
