### ISSUE TITLE
Weird errors with QEMU

### ISSUE THREAD

**Issue by jlagarespo** [cfenollosa/os-tutorial#103]
Ok, first of all i only tested this with qemu.
I am compiling with gcc and linking with ld, basically because i wasn't able to install the crosscompiler for windows.
The first kernel barebones thing worked perfectly. It just printed an "X" at the top of the screen as it should. But here comes the problem: i just *exacly* copypasted the kprint code (it didn't work with my version of it) and it does nothing. Nothing appears at the screen at all. Surprisinhly enough, clear_screen() function works just fine, and i can change the color of it and it still does work just fine.
Please can someone help me?

**Comment by aclogreco** [comment]
I was having a similar issue. I solved it by increasing the number of sectors read in bootsect.asm (line 31).  I did not notice that I was still only reading 2 sectors and my kernel was not being completely read into memory. This might be the source of your issue, as well. Try increasing the size and see if that helps.

**Comment by jlagarespo** [comment]
Thanks it solved my problem :)
I am kinda blind sometimes sorry. Closing issue.

**Comment by aclogreco** [comment]
@jlagarespo No worries! Glad I could help. Don't feel bad about not catching that. I spent about an hour or so running the debugger and trying a bunch of stuff before I found the answer in another issue thread on here.
