### ISSUE TITLE
Please update the link for JamesM's Tutorial

### ISSUE THREAD

**Issue by HrushikeshK** [cfenollosa/os-tutorial#11]
The following link is mentioned in Chapter 18-Interrupts and is not available
http://www.jamesmolloy.co.uk/tutorial_html/index.html

**Comment by cfenollosa** [comment]
It seems that the server was reinstalled and the page is no longer available. I'll change it to the archived link. Thanks for reporting this.

**Comment by HrushikeshK** [comment]
The link's working fine now :+1:
I have a query regarding the GDT. Why didn't we write GDT in C itself? 
Or is it that we need to create GDT before we load kernel?

**Comment by cfenollosa** [comment]
I don't have a specific answer. I was following a couple tutorials and that was the way they did them. For what I've read, this project heavily mixed assembler and C; many other tutorials are very C-specific or asm-specific. Anyway, there is no reason, it's just the way it is :)

**Comment by HrushikeshK** [comment]
Okay. 
Thank You :+1:
