### ISSUE TITLE
How to install i386-elf-gcc in ubuntu16.04

### ISSUE THREAD

**Issue by waytai** [cfenollosa/os-tutorial#114]
make: /usr/local/i386elfgcc/bin/i386-elf-gcc: Command not found

**Comment by jlagarespo** [comment]
Google.
Also, [this](https://wiki.osdev.org/GCC_Cross-Compiler) might be helpful.

**Comment by waytai** [comment]
I am in china, and can not use google

**Comment by jlagarespo** [comment]
❓ 
Wait what. Is google seriously banned in china??

**Comment by jlagarespo** [comment]
I mean, if you have to deal with the firewall, building a cross-compiler will be kinda of hard tbh...

**Comment by jlagarespo** [comment]
Do you have access to a VPN or something?

**Comment by zombiepigdragon** [comment]
If you can access GitHub, Google should be available...
If you can't get to Google, just use any search engine

**Comment by waytai** [comment]
thank you

**Comment by waytai** [comment]
is there any replacement of the i386-elf-gcc in Makefile for ubuntu16.04?

**Comment by jlagarespo** [comment]
Straightup regular gcc? But trust me, use a crosscompiler don't use linux gcc, because althought your OS might be similar to linux, IT IS NOT it, so use a crosscompiler. Also, are you sure you want to target i386? That is kindaof old isn't it? I'd honestly better target something like i686, or x86-64...

**Comment by BaselNsralla** [comment]
I had trouble with it, modified https://gist.github.com/preshing/41d5c7248dea16238b60
to https://gist.github.com/BaselNsralla/2cad77e35ab37b677a87249912d5eb83
and now it works.

**Comment by Matthiasclee** [comment]
Try installing with homebrew https://github.com/nativeos/homebrew-i386-elf-toolchain

**Comment by jlagarespo** [comment]
Bad idea, you should always build your own crosscompiler. If this tutorial doesn't work then I recommend this: https://wiki.osdev.org/GCC_Cross-Compiler

**Comment by rakshit087** [comment]
Hey I am facing same issue while using https://github.com/nativeos/i386-elf-toolchain/releases
what is the solution?

**Comment by swap2ag** [comment]
I have cross-compiled this on Ubuntu. You can download the archive from https://drive.google.com/file/d/1YvkTMPKsFtyFXGviWyArsu5G8C9HHY3D/view?usp=sharing. 

I take no guarantee that this will work as expected but it works on my machine.

**Comment by rakshit087** [comment]
Thanks a lot. It saved a lot of my time and yes it is working

**Comment by swap2ag** [comment]
I have created a gist in case you want to compile the cross-compiler yourself. Use the github codespaces and the gist at 

<script src="https://gist.github.com/swap2ag/1e9627974a19defa291e748affe5803f.js"></script>

**Comment by killeradhil** [comment]
how i install x86_64-elf-gcc on debian, i cant install like sudo apt install x86_64-elf-gcc

**Comment by sekrittt** [comment]
> how i install x86_64-elf-gcc on debian, i cant install like sudo apt install x86_64-elf-gcc

Please try to install gcc and use it. Additional command arguments may be needed.

**Comment by killeradhil** [comment]
In bash script what i should replace instread of x86_64 gcc- elf?

**Comment by sekrittt** [comment]
> In bash script what i should replace instread of x86_64 gcc- elf?

If you are using a Makefile, replace the value of _CC_ with _gcc_.
If you use bash-script, please use the _gcc_ command.
The **-m32** argument of the _gcc_ command compiles in 32-bit mode, the default is 64-bit.
