### ISSUE TITLE
Compiler using weird opcodes?

### ISSUE THREAD

**Issue by jlagarespo** [cfenollosa/os-tutorial#115]
Ok, I know this might seem bizarre, but i really can't understand it, and I don't really know how to approach this problem. I tried debugging but no results so far.
Now here's the issue:
Given this code:
```c
int screen_size = MAX_COLS * MAX_ROWS;
char *screen = VIDEO_ADDRESS;

for (int i = 0; i < screen_size; i++) {
    screen[i*2] = '\0';
    screen[i*2+1] = WHITE_ON_BLACK;
}
set_cursor_offset(get_offset(0, 0));
```
###### (suposed to clear the screen)
the variable ``i`` keeps itself at 0, even when I'm ``i++``ing, so only the first char on te screen gets cleared.
I tried making it ``static``, but it didn't really seem to help much.
Of course, i checked that everything was setup correctly, and indeed, if i manually accessed video memory like this:
```c
// Arbitrary value means "0xb8000 + my custom offset"...
screen[arbitarary_value] = 'X';
```
it in fact worked!
The thing is, this is not the only place where the issue is appearing: in other places it is too.
I shall say, that I am not using the same envinroment as this tutorial: I'm using multiboot instead of barebones, with GRUB2, and my system is also 64bit. I don't thing this has much to do with it, as everything else works nicely but whatever. This is my full C compilation command for every *.c file:
```sh
gcc -O2 -pipe -Wall -Wextra -m64 -std=gnu99 -masm=intel -fno-pic -fno-PIE -mno-sse -mno-sse2 -mno-red-zone -mcmodel=kernel -ffreestanding -fno-stack-protector -I./ -c src/kernel/main.c -o src/kernel/main.o
```
###### (this one is for the kernel.c file, but the makefile it should automatically do it for every c file)
Any help would be extremly appreciated, thanks!

**Comment by gurixrathore** [comment]
We're missing some information here. Mind sharing the values for MAX_COLS
and MAX_ROWS?

**Comment by jlagarespo** [comment]
Ok yeah, i might have to clarify some extra stuff here:
```c
#define MAX_ROWS 25
#define MAX_COLS 80
```
that's ``MAX_ROWS`` and ``MAX_COLS``.
If the preprocessor is working right it should replace ``MAX_ROWS`` with 25 and so with ``MAX_COLS``.
And yeah, i probably have an infinite loop.
Also, similar stuff happened in other places, specially with pointer not incrementing when ``++ptr`` and so on and so forth.
For example:
This works:
```c
screen[0] = 'H';
screen[2] = 'e';
screen[4] = 'l';
screen[6] = 'l';
screen[8] = 'o';
```
but this doesn't:
```c
char *screen = (char*)0xb8000;
const char *str = "Hello";
int i;
while(str[i] != '\0') {
   *screen = str[i];
   screen += 2;
   ++i;
}
```
###### I know theres more efficient and cleaner ways to do this, but this was just for illustrative purposes.
In this case the output would be an ``'o'`` at the first character on the screen.
I hope I clarified your questions!

**Comment by gurixrathore** [comment]
Thanks for the clarification. The issue does not seem to be with incrementing i, as that seems to have worked fine in the second case. The issue is not even with pointer addition, as that seems to be working fine with str. The issue seems to be limited to writing to screen offset using a variable. Strangely, the same works fine when you use constants. I would say try making screen a const in the first example. That is something that did work in the second case, where str was a const. If that works, then you have narrowed down the problem to non-const pointer offsetting.

**Comment by jlagarespo** [comment]
I mean, the first case just works fine, and if i turn it into const, wouln't it not allow me to use it?
Like
```c
const char* screen = (const char*)0xb8000;
screen[2] = 'A';
```
I am pretty sure that the compiler would prevent you from editing a const pointer...
Also, the second case doesn't work either.
I am pretty sure it has something to do with the compiler or the linker, because i literally copy-pasted code written by @cfenollosa and it still didn't clear the screen.
I will look at the dissasembly to see EXACLY what the C compiler is converting my code to.

**Comment by jlagarespo** [comment]
I mean, the first case just works fine, and if i turn it into const, wouln't it not allow me to use it?
Like
```c
const char* screen = (const char*)0xb8000;
screen[2] = 'A';
```
I am pretty sure that the compiler would prevent you from editing a const pointer...
Also, the second case doesn't work either.
I am pretty sure it has something to do with the compiler or the linker, because i literally copy-pasted code written by @cfenollosa and it still didn't clear the screen.
I will look at the dissasembly to see EXACLY what the C compiler is converting my code to.

**Comment by jlagarespo** [comment]
I think i found the issue. Please, zoom in and read the comments on the dissasembly...
![Screenshot from 2019-05-15 16-31-04](https://user-images.githubusercontent.com/26935885/57783877-3782d480-772f-11e9-948d-866787000661.png)

**Comment by gurixrathore** [comment]
You indeed cannot modify a const pointer, i.e. the pointer will always point to the same location...BUT you can modify the contents of the memory pointed to by a const pointer, which is what you are doing in the first example.

In any case, I looked at the assembly you shared. I don't see anything wrong there actually. JNZ should work in this case as it is proceeding with adding 2 to rax until it matches the target value. Am I missing something here?

**Comment by jlagarespo** [comment]
JNZ should jump if the value is not zero. It is always more than 0xB8000, so it is NEVER zero. Which makes the condition true, making it jump just in the first loop iteration, explaining the only character written in the screen... the question would be, why is the compiler doing this?

**Comment by gurixrathore** [comment]
Actually I think JNZ should look at the flags after the CMP operation.

**Comment by gurixrathore** [comment]
You didn't write a not equals comparison. But the C compiler sometimes does
this sort of optimizations, to reduce the number of operations. I haven't
thought in detail about it, but it's clear that the C compiler added 4000
(80*25)*2 to the start address and stops when you match it. If it had to
use < operation, then it should have added 4001 instead.

**Comment by jlagarespo** [comment]
I mean, that's what i was saying about optimizations above, it would make sense that the optimizer messed up somehow... althought that seems incredibly bizarre to me, as nothing like this ever happend(at least to me) before... in any way, i am pretty sure that if it tries to compare rax to 0xb8whatever, and we assume that ZF is set properly, acting as EF, we it should use ``JZ`` instead of ``JNZ`` because in any way, we want to JUMP IF EQUAL, not if not equal... idk if any of that made any sense, maybe i am just being very stupid but whatever. The point is: it only replaces the first character of the screen, which is weird, considering i LITERALLY copypasted cfenollosa's code(maybe is it because i am using 64bit instead of 32? That shouldn't really matter when it comes to comparasions right???)

**Comment by gurixrathore** [comment]
Again, JNZ is the correct instruction. You're jumping from the bottom back to the top of the loop unless the result of comparison is zero. So Jump_if_Not_Zero (JNZ) and once the result is zero we stop jumping. Makes sense?

**Comment by jlagarespo** [comment]
Wait a minute... i just realized I am stupid, I was thinking JNZ jumped into another addr- i am so blind.
Then i really can't understand what is happening here honestly, the dissasembly seems right. I just thought that JNZ was jumping OUTSIDE of the loop if it didn't... anyways, just ignore me, sometimes i am either blind or stupid 🤦‍. Then honestly I don't know what could be going wrong here, I must really investigate furtherer. I will try to disable ALL optimizations of the compiler, and try to debug it with gdb, but because it is loaded dynamically by GRUB2, then it might be hard to set breakpoints(i'll just have to write down the addresses of instructions i wanna break on), and also, my knowledge on gdb is not very great, so oh well, I'll see what i can do...

**Comment by jlagarespo** [comment]
I legitimatelly can't believe it.
I was right, optimizer messed up.
I literally disabled it for debugging and... voila. Screen cleared.
Why thought? I have no idea, im sure im using lastest gcc(my crosscompiler is not yet ready), and I should also look at the dissasembly differences between the optimized version and the not optimized one...

**Comment by jlagarespo** [comment]
Hmm when i call kprint it crashes tho, this is all so weird...

**Comment by gurixrathore** [comment]
This issue is becoming more and more interesting!

Can you share the assembly with the optimizer turned off? There has to be a clue in the difference between the two versions.

**Comment by jlagarespo** [comment]
With optimization:
![Screenshot from 2019-05-17 18-23-33](https://user-images.githubusercontent.com/26935885/57942291-5325e080-78d1-11e9-88c5-6d9a90feff85.png)
Without optimization:
![Screenshot from 2019-05-17 18-22-21](https://user-images.githubusercontent.com/26935885/57942299-5f11a280-78d1-11e9-8ccf-83d745d21a86.png)
Maybe it is just because it is comparing RAX to be 0xb8whatever and it never gets there, i mean it's adding two each time, so could it be that it just skips that one by adding two?
Using a confitional like JGE(jump if greater or equal) would likely fix it. And i am pretty sure it is as preformant as JNZ, as it just checks flags right? I don't know why did the people at GCC thought that doing that was a good optimization thing? Anyways, that might be or might not be the issue, and I still have to debug honestly. Surely this is interesting, might this be a GCC optimization bug? But then why does it work on cfenollosa's code? Might this be a GCC 64-bit bug? That surely requires furtherer investigation...

**Comment by gurixrathore** [comment]
Adding 2 each time will not skip over the final value because the optimizer has already multiplied the final value accordingly. You may remember I had said this at one point: "I haven't thought in detail about it, but it's clear that the C compiler added 4000, i.e. (80*25)*2 to the start address and stops when you match it. ". That *2 is what ensures that the value that we are comparing with is the correct 2's multiple. So that is not the problem here.

I wonder if the issue has anything to do with the fact that the optimizer used eax to initialize the register with pointer value but then switched to using rax instead during. There seem to be some notorious issues with that sort of thing. For example, see here: https://stackoverflow.com/questions/25455447/x86-64-registers-rax-eax-ax-al-overwriting-full-register-contents

**Comment by jlagarespo** [comment]
Hmm, I am not in a 32 bit system, i would have to do cross-compiling for this. Maybe I'll try corsscompiling for x86-64 in my system(although i don't really know the difference from using GCC in my host system, as it is already 64-bit...) Anyway, I'll try replacing that EAX with RAX, and see if it solves the issue...

**Comment by gurixrathore** [comment]
You could use gcc -m32 flag to generate 32 bit code. 32 bit code should work without change on 64 bit processor.

**Comment by gurixrathore** [comment]
Actually never mind. Thinking again about it, 32 bit code will probably not work on 64 bit processor because of the smaller instruction length. Let me know your findings though

**Comment by jlagarespo** [comment]
Hmm, I've actually been investigating on this and I've been dissasembling code generated by gcc, some working, some not. There's some interesting stuff, but i think this whole issue is just a problem of architectures... I will be closing this for the moment. I want to start anyways implementing a scheduler and basic stuff like that, but i can't if i don't have an output system to test it and dump out values. In any way, i think disabling optimizations is for now the way to go... and of crouse -m32 didn't actually work. Thanks for everything thoguht!

**Comment by SleepMod** [comment]
Its harder créate, or say me something another time boe? Remember me? Ho espero :) Eh tio, bon codi, espero que tornis una altra vegada a la comunitat de sicord. El meu tag "! SleepMod !#6734"
