### ISSUE TITLE
there is something wrong?

### ISSUE THREAD

**Issue by root00r** [cfenollosa/os-tutorial#118]
when I define 1M bytes in stack,kernel has something wrong.
like this:
void main() {
    char str[1024*1024];
    ....
}

so I change the code in boot/switch_pm.asm

[bits 32]
init_pm: ; we are now using 32-bit instructions
    ....
    mov ebp, 0x900000 ; <----------change 0x90000 to 0x900000
    mov esp, ebp
    ...

then kernel run successed.
this is a bug?

**Comment by sjx233** [comment]
The stack grows downwards, so if the stack pointer is at `0x90000` initially, its size is at most 576KB, and a 1MB array would not fit in it. Changing `esp` to `0x900000` increases the size of the stack to up to 9MB, which solves this problem.

**Comment by root00r** [comment]
> The stack grows downwards, so if the stack pointer is at `0x90000` initially, its size is at most 576KB, and a 1MB array would not fit in it. Changing `esp` to `0x900000` increases the size of the stack to up to 9MB, which solves this problem.

yeah,you are right, I think the kernel stack size should be bigger than 1MB,so esp shoule be set 0x900000 in the boot/switch_pm.asm `file.
```[bits 32]
init_pm: ; we are now using 32-bit instructions
....
mov ebp, 0x900000 ; <----------change 0x90000 to 0x900000
mov esp, ebp
...

**Comment by Menotdan** [comment]
> > The stack grows downwards, so if the stack pointer is at `0x90000` initially, its size is at most 576KB, and a 1MB array would not fit in it. Changing `esp` to `0x900000` increases the size of the stack to up to 9MB, which solves this problem.
> 
> yeah,you are right, I think the kernel stack size should be bigger than 1MB,so **esp** shoule be set **0x900000** in the boot/switch_pm.asm file.

Yes that is correct. The stack can be anywhere in between those points but if you want the most space, then you should leave it there, since you don't have a memory map, you don't know what memory is safe.

**Comment by jlagarespo** [comment]
> since you don't have a memory map
I think that should be the next tutorial: using the BIOS to get a memory map and how to interpret it.

**Comment by Menotdan** [comment]
Yeah. In my os (https://github.com/Menotdan/DripOS) I just switched to GRUB cuz I ran out of space (increasing `ah` before the read did not help), and because free boot information.

**Comment by jlagarespo** [comment]
Yeah, that's what you should do when you have a more serious OS, but this tutorial is meant for begginers, so I think it's fine for it to stick with regular legacy BIOS boot

**Comment by Menotdan** [comment]
> Yeah, that's what you should do when you have a more serious OS, but this tutorial is meant for begginers, so I think it's fine for it to stick with regular legacy BIOS boot

The funny thing-i literally learned C from this tutorial
I did python for like 2 years before that
and then I just started an OS from this tutorial
and I learned C from this tutorial
and now im decent at it
