### ISSUE TITLE
Can I write a Chinese version like this?

### ISSUE THREAD

**Issue by ghost** [cfenollosa/os-tutorial#123]
Hi, I am a kernel lovers, after reading this tutorial, I think it's a good way to do it, so I plan to write a Chinese version, I hope to get your authorization.

**Comment by lebel-louisjacob** [comment]
Hi @Richyeohx, you shouldn't need the authorization of anyone to do this. Have a look at the /LICENSE file for more info.

Also, you might want to fork this repository so that chinese people ending up on this repository can find yours with more ease.

**Comment by Richyeohx** [comment]
> I will start this work in the near future. I wonder if anyone has started now.

Yes，I've already started, But I not upload Github.

**Comment by haiyonghao** [comment]
> > I will start this work in the near future. I wonder if anyone has started now.
> 
> Yes，I've already started, But I not upload Github.

not upload吗？哈哈哈. 这语法太秀了.
I've translated some pieces, also not on github.
I put them on my csdn blog: https://blog.csdn.net/haiyonghao/article/category/9338336
If I got enough time, I'll compose them on my github.

**Comment by Richyeohx** [comment]
> > > I will start this work in the near future. I wonder if anyone has started now.
> > 
> > 
> > Yes，I've already started, But I not upload Github.
> 
> not upload吗？哈哈哈. 这语法太秀了.
> I've translated some pieces, also not on github.
> I put them on my csdn blog: https://blog.csdn.net/haiyonghao/article/category/9338336
> If I got enough time, I'll compose them on my github.

老哥，淡定点，This is gayhub，你会让我很尴尬的。

**Comment by Richyeohx** [comment]
> > > I will start this work in the near future. I wonder if anyone has started now.
> > 
> > 
> > Yes，I've already started, But I not upload Github.
> 
> not upload吗？哈哈哈. 这语法太秀了.
> I've translated some pieces, also not on github.
> I put them on my csdn blog: https://blog.csdn.net/haiyonghao/article/category/9338336
> If I got enough time, I'll compose them on my github.

应该用did't是么

**Comment by haiyonghao** [comment]
> > > > I will start this work in the near future. I wonder if anyone has started now.
> > > 
> > > 
> > > Yes，I've already started, But I not upload Github.
> > 
> > 
> > not upload吗？哈哈哈. 这语法太秀了.
> > I've translated some pieces, also not on github.
> > I put them on my csdn blog: https://blog.csdn.net/haiyonghao/article/category/9338336
> > If I got enough time, I'll compose them on my github.
> 
> 应该用did't是么

哈哈哈哈，随便什么，能看懂就行.
Don't worry, be happy.

**Comment by Richyeohx** [comment]
> > > > > I will start this work in the near future. I wonder if anyone has started now.
> > > > 
> > > > 
> > > > Yes，I've already started, But I not upload Github.
> > > 
> > > 
> > > not upload吗？哈哈哈. 这语法太秀了.
> > > I've translated some pieces, also not on github.
> > > I put them on my csdn blog: https://blog.csdn.net/haiyonghao/article/category/9338336
> > > If I got enough time, I'll compose them on my github.
> > 
> > 
> > 应该用did't是么
> 
> 哈哈哈哈，随便什么，能看懂就行.
> Don't worry, be happy.

好的呢。
Good good study,day day up.

**Comment by pooolman** [comment]
@Richyeohx @haiyonghao @ydcool 
hello, guys. I'm already had completed a mini-os-kernel with neassary features(filesystem/multiprocess/simple shell with pipe) and a detailed design document. Rencently I'm constructing a toturial in Chinese which has more features than this one.  Would you want to join together?  I'm welcome your participation ^_^

**Comment by ydcool** [comment]
@pooolman sounds great, and how could we join you?

**Comment by Richyeohx** [comment]
> @pooolman sounds great, and how could we join you?

Me to.

**Comment by haiyonghao** [comment]
> @Richyeohx @haiyonghao @ydcool
> hello, guys. I'm already had completed a mini-os-kernel with neassary features(filesystem/multiprocess/simple shell with pipe) and a detailed design document. Rencently I'm constructing a toturial in Chinese which has more features than this one. Would you want to join together? I'm welcome your participation ^_^



> @pooolman sounds great, and how could we join you?
how can we contact you ?

**Comment by eamanu** [comment]
Welcome to open source :)

**Comment by pooolman** [comment]
I'm so sorry that I didn't reply you in time. I didn't got an appropriate cooperation method after some time of thinking. So probably there is more diffcult to write a toturial together than i expected.
Today I have uploaded the project to github that include sources, configure files and detailed documents. Subsequent tutorial is still under development. It's still welcome once you have some good ideas to collaborate each others and please open an issue on my project to let me know. Thanks.

**Comment by pooolman** [comment]
@Richyeohx @ydcool @haiyonghao 
I'm so sorry that I didn't reply you in time. 
I didn't got an appropriate cooperation method after some time of thinking. So probably there is more diffcult to write a toturial together than i expected.
Today I have uploaded the project to github that include sources, configure files and detailed documents. Subsequent tutorial is still under development. It's still welcome once you have some good ideas to collaborate each others and please open an issue on my project to let me know. Thanks.

**Comment by pooolman** [comment]
[https://github.com/pooolman/tryos](url)

**Comment by Veeupup** [comment]
Hi, I want to join you guys, but I am busy this time. I can start to work in late December, can I join you?

**Comment by haiyonghao** [comment]
> Hi, I want to join you guys, but I am busy this time. I can start to work in late December, can I join you?

of course, please show us your **wechat account name**, I will make a group and pull you guys in.

**Comment by Veeupup** [comment]
> > Hi, I want to join you guys, but I am busy this time. I can start to work in late December, can I join you?
> 
> of course, please show us your **wechat account name**, I will make a group and pull you guys in.

thanks  my wechat account is  tanweime.

**Comment by J2is18cm** [comment]
all of you are dalao,but i am a cookie and still studing assembly language.....

**Comment by cfenollosa** [comment]
Sure, feel free to fork this repo for a Chinese version. Thanks for your interest!
