### ISSUE TITLE
I want to translate this os-tutorial ! 

### ISSUE THREAD

**Issue by kimkyungbae** [cfenollosa/os-tutorial#126]
hi ! ,  I am student in Korea . I hope to see os-tutorial many koreans.  so i want to translate os-tutorial ! please give me your authorization.

**Comment by fky2015** [comment]
Hello! Same as  discussion in #123, you don't have to get authorization from anyone as the [licence](https://github.com/cfenollosa/os-tutorial/blob/master/LICENSE) has already give you.

FYI, I quote the [comment](https://github.com/cfenollosa/os-tutorial/issues/123#issuecomment-522992519) from `lebel-louisjacob`

> Hi @Richyeohx, you shouldn't need the authorization of anyone to do this. Have a look at the license file for more info.
> Also, you might want to fork this repository so that chinese people ending up on this repository can find yours with more ease (but that's up to you).

**Comment by cfenollosa** [comment]
Sure, feel free to fork the repo. Thanks for your contribution to the community.
