### ISSUE TITLE
Expression syntax error, chapter 1

### ISSUE THREAD

**Issue by WeeRox** [cfenollosa/os-tutorial#13]
When trying to run `nasm -f bin boot_sect_simple.asm -o boot_sect_simple.bin` I got two exceptions of the same type: expression syntax error. 
I searched the Internet and managed to fix the problem, I had to rename the loop variable to loop1 and then it worked!

**Comment by mickberber** [comment]
Did you run into this problem as well?

```
➜  simple-os qemu-system-x86_64 boot_sect_simple.bin 
WARNING: Image format was not specified for 'boot_sect_simple.bin' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
^Cqemu-system-x86_64: terminating on signal 2 from pid 14720 (<unknown process>)
```

**Comment by WeeRox** [comment]
No, I don't think so, I can't quite remember but that seems like it is a different error message than I got.

**Comment by cfenollosa** [comment]
Sorry for the late reply.
Maybe some `nasm` version has "loop" as a reserved keyword, which should not be the case. 
Thanks for taking the time to report this.
