### ISSUE TITLE
Question about pusha and popa 

### ISSUE THREAD

**Issue by skyf0cker** [cfenollosa/os-tutorial#133]
i am a beginner to Assembly,i am just curious about the following Questions. If i can get your help, i will appreciate it!
 we see that when we use stack we init the stack by setting the value of bp and sp, but when we use pusha and popa, who set the position of our stack?

i am confused about this!
thank you guys!

**Comment by jlagarespo** [comment]
PUSHA (push all), pushes all general purpose registers (EAX, EBX, ECX, EDX, ESI, EDI, ESP before the push and EBP) to the stack. It is equivalent to:
```x86asm
push eax
push ebx
push ecx
push edx
...
```
Except that it happens instantly, so it'd probably be more like
```x86asm
mov [esp], eax
mov [esp-4], ebx
mov [esp-8], ecx
mov [esp-12], ecx
...
sub esp, (8*4) ; 8 is the number of registers we pushed, and 4 is the size of each of them in bytes.
```
(Warning: this is pseudo-assembly that I'm writing here to explain the point, it will probably not compile with common assemblers)
It is used to quickly save all registers, which can be poped by POPA.
> but when we use pusha and popa, who set the position of our stack?

Of course, the position of SP is set by the PUSHA and POPA instructions themselves, as that's all that "poping and pushing" from the stack really means: reading/writing a value to whatever ESP is pointing at ([esp] in intel syntax *esp in at&t) and increasing/decerasing ESP.

Hope this clarifies things!

**Comment by jlagarespo** [comment]
http://faydoc.tripod.com/cpu/pusha.htm

**Comment by skyf0cker** [comment]
> PUSHA (push all), pushes all general purpose registers (EAX, EBX, ECX, EDX, ESI, EDI, ESP before the push and EBP) to the stack. It is equivalent to:
> 
> ```
> push eax
> push ebx
> push ecx
> push edx
> ...
> ```
> 
> Except that it happens instantly, so it'd probably be more like
> 
> ```
> mov [esp], eax
> mov [esp-4], ebx
> mov [esp-8], ecx
> mov [esp-12], ecx
> ...
> sub esp, (8*4) ; 8 is the number of registers we pushed, and 4 is the size of each of them in bytes.
> ```
> 
> (Warning: this is pseudo-assembly that I'm writing here to explain the point, it will probably not compile with common assemblers)
> It is used to quickly save all registers, which can be poped by POPA.
> 
> > but when we use pusha and popa, who set the position of our stack?
> 
> Of course, the position of SP is set by the PUSHA and POPA instructions themselves, as that's all that "poping and pushing" from the stack really means: reading/writing a value to whatever ESP is pointing at ([esp] in intel syntax *esp in at&t) and increasing/decerasing ESP.
> 
> Hope this clarifies things!

This is really useful!
thanks for your time
