### ISSUE TITLE
Is there anyone want to do a memory management or a simple filesystem?

### ISSUE THREAD

**Issue by Veeupup** [cfenollosa/os-tutorial#135]
I appreciate a lot from this repo, but this repo did not finish a memory management or a simple file system.
I alone am not able to finish it, but I have great passion in creating it. Is there anyone who excels in C want to finish it with me?

**Comment by AtieP** [comment]
I don't know a lot of C, but i recommend you to create a FAT filesystem using assembly. You won't regret it.

**Comment by Menotdan** [comment]
Actually, qword's echfs is pretty good too, and for memory management, you probably want a page allocator, especially if you want x86_64 later on

**Comment by Menotdan** [comment]
But for that it might be better to start from scratch

**Comment by Veeupup** [comment]
thanks for your advice, I will try it.
