### ISSUE TITLE
Qemu error

### ISSUE THREAD

**Issue by Leppan** [cfenollosa/os-tutorial#14]
In the first chapter, it tells me to run qemu boot_sect_simple. However, the actual command is qemu-system-x86 (or something similar).

**Comment by cfenollosa** [comment]
Already explained here: https://github.com/cfenollosa/os-tutorial/tree/master/00-environment

Thanks!

**Comment by Leppan** [comment]
On Linux.
The last part specifically says "on Mac", whereas this happens on Linux too.

**Comment by cfenollosa** [comment]
Didn't know that. Updated, thanks
