### ISSUE TITLE
Is there a active or more advanced fork?

### ISSUE THREAD

**Issue by LeMoonStar** [cfenollosa/os-tutorial#145]
The tutorial is still missing a complete memory allocation system, filesystem and many other important things. And as stated in issue #39 it is not actively worked on. He said he would add a link to the "main-fork" in the readme if people are interested, but that never happend. So, is there a fork which is active/more advanced?

**Comment by kis-balazs** [comment]
+1, I would be also interested in it too :DD

**Comment by sakshatshinde** [comment]
+1, Same actually. I am currently referencing this for my university project, so would be glad if someone has a well maintained fork with further topics implemented.

**Comment by Menotdan** [comment]
well i mean, this tutorial isnt really the best lol
there is a way better approach to take for OSdev, one thing being epic 64 bit mode
you can look at [DripOS](https://github.com/Menotdan/DripOS) for an example, although the code is kinda messy and its not really a tutorial so meh, you should probably use the [OSdev wiki](https://wiki.osdev.org/Main_Page), also feel free to come to the epic [OSdev discord](https://discord.gg/RnCtsqD) where we have epic memes and epic smart people who know how to help you lol

**Comment by XE54Dev** [comment]
@Menotdan epic
