### ISSUE TITLE
Cannot run 'make' on lesson 24 folder

### ISSUE THREAD

**Issue by phathung2001** [cfenollosa/os-tutorial#153]
When I ran 'make' on the lesson 18's folder (and all other lessons til 24) I got this error:
```
i386-elf-ld -o kernel.bin -Ttext 0x1000 boot/kernel_entry.o kernel/kernel.o cpu/interrupt.
o drivers/keyboard.o drivers/screen.o cpu/idt.o cpu/isr.o cpu/ports.o cpu/timer.o libc/mem
.o libc/string.o --oformat binary
i386-elf-ld: cpu/isr.o:/Users/ngocphat/git/os-tutorial/24-el-capitan/cpu/idt.h:31: multipl
e definition of `idt'; cpu/idt.o:/Users/ngocphat/git/os-tutorial/24-el-capitan/cpu/idt.h:3
1: first defined here
i386-elf-ld: cpu/isr.o:/Users/ngocphat/git/os-tutorial/24-el-capitan/cpu/idt.h:32: multipl
e definition of `idt_reg'; cpu/idt.o:/Users/ngocphat/git/os-tutorial/24-el-capitan/cpu/idt
.h:32: first defined here
make: *** [kernel.bin] Error 1
```
i386-elf-* binaries are installed as described in lesson ``11-kernel-crosscompiler``, but I used gcc 10.1.0 instead of 4.x.
I'm using macOS Mojave 10.14.6.

**Comment by Matthiasclee** [comment]
I have the same problem. Maybe try to use this bash script to compile even though you need to edit it whenever you add a new file it works for me


#define variables
ne="false"
fn="OS.bin"
lf="false"
eroc="true"
#check for any parameters
if [[ $# == 0 ]]; then
	echo
	else
	aa=$@
	if [[ $1 = -* ]]; then
		echo
	else
		fn=$1
	fi
	if [[ $aa == *"-noexec"* ]]; then
		ne=true
	fi

	if [[ $aa == *"-lf"* ]]; then
		lf=true
	fi

	if [[ $aa == *"-help"* ]]; then
		eroc=false
		echo --------------------------------------------------------------------
		echo ---------------------------All Parameters---------------------------
		echo --------------------------------------------------------------------
		echo -noexec  Compile without executing in qemu
		echo -lf  Leave extra .o and .bin files in the main directory
		echo -ef  Erase extra files
	fi
	if [[ $aa == *"-ef"* ]]; then
		eroc=false
		rm *.o
rm kernel.bin
rm bootsect.bin
echo Cleaned up extra files
	fi
fi


if [[ $eroc == "true" ]]; then
#compile all .c files into .o files
i386-elf-gcc -ffreestanding -c kernel/kernel.c -o kernel.o
i386-elf-gcc -ffreestanding -c drivers/screen.c -o screen.o
i386-elf-gcc -ffreestanding -c drivers/ports.c -o ports.o
i386-elf-gcc -ffreestanding -c kernel/util.c -o util.o
i386-elf-gcc -ffreestanding -c cpu/idt.c -o idt.o
i386-elf-gcc -ffreestanding -c cpu/isr.c -o isr.o
i386-elf-gcc -ffreestanding -c drivers/keyboard.c -o keyboard.o
i386-elf-gcc -ffreestanding -c cpu/timer.c -o timer.o
#compile some asm files into .o files
nasm cpu/interrupt.asm -f elf -o interrupt.o
nasm boot/kernel_entry.asm -f elf -o kernel_entry.o
# link all the .o files into one .bin
i386-elf-ld -o kernel.bin -Ttext 0x1000 kernel_entry.o kernel.o ports.o screen.o util.o idt.o isr.o keyboard.o interrupt.o timer.o --oformat binary
#compile the bootsector
nasm boot/bootsect.asm -f bin -o bootsect.bin

#link the bootsector and kernel into one file
cat bootsect.bin kernel.bin > $fn
#check if the user wants to clean up the extra files
if [ $lf == "false" ]
	then
	   
#clean up extra files
rm *.o
rm kernel.bin
rm bootsect.bin
fi

#check if user wants to run qemu
if [ $ne == "false" ]
then
#run qemu
   qemu-system-i386 -fda $fn
   
fi


#print Finished message
echo Finished
fi

**Comment by jinevitable1** [comment]
Here's the solution to the problem above. If you add static inline to the code on line 31 and 32 in the idt.h header file, it will work and you can run makefile again. Code is listed below.  Add it to idt_gate_t and idt_register_t. 

 `#define IDT_ENTRIES  256

static inline  idt_gate_t   idt  [IDT_ENTRIES];
static inline  idt_register_t   idt_reg;`

**Comment by phathung2001** [comment]
> Here's the solution to the problem above. If you add static inline to the code on line 31 and 32 in the idt.h header file, it will work and you can run makefile again. Code is listed below. Add it to idt_gate_t and idt_register_t.
> 
> `#define IDT_ENTRIES 256
> 
> static inline idt_gate_t idt [IDT_ENTRIES];
> static inline idt_register_t idt_reg;`

This solution worked for me. Thank you very much!
