### ISSUE TITLE
21-shell kprint_backspace

### ISSUE THREAD

**Issue by Matthiasclee** [cfenollosa/os-tutorial#157]
When I compile and run the code from lesson 21, i get an error:
`keyboard.o: In function keyboard_callback:
keyboard.c:(.text+0x37): undefined reference to kprint_backspace
cat: kernel.bin: No such file or directory
`
But when I comment out "kprint_backspace" in keyboard.c it works fine although I can not erase characters.

Also, when I run the compiles os-image.bin with the error, it is stuck in a boot loop.

**Comment by jinevitable1** [comment]
did you include the keyboard and screen headers in keyboard.c?  kprint_backspace is defined in screen.c.
