### ISSUE TITLE
Do you switch the 32 protected mode successfully?

### ISSUE THREAD

**Issue by duanbing** [cfenollosa/os-tutorial#168]
I ran the lesson 10,  and get the output below:

![image](https://user-images.githubusercontent.com/3865728/87865649-9898de80-c9aa-11ea-91ca-b1f747f5429e.png)

and hangs here without showing the message `Loaded 32-bit protected mode`.

Env info:
```
$ qemu-system-x86_64 --version
QEMU emulator version 5.0.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

**Comment by duanbing** [comment]
I think the switch had been done, but the signal message just not show as expected.

**Comment by TLHorse** [comment]
You are right. I tried it too, the process just wouldn't switch into 32bit mode. Who knows?

**Comment by duanbing** [comment]
@TLHorse  it works for me now.  
For less 10, enjoy it as below:
```
nasm -f bin ./32bit-main.asm  -o 32bit-main.bin
qemu-system-x86_64 -fda 32bit-main.bin
```
Then another terminal will pop up and show what you want.

**Comment by TLHorse** [comment]
> @TLHorse it works for me now.
> For less 10, enjoy it as below:
> 
> ```
> nasm -f bin ./32bit-main.asm  -o 32bit-main.bin
> qemu-system-x86_64 -fda 32bit-main.bin
> ```
> 
> Then another terminal will pop up and show what you want.

Thanks for the reply, actually I did switch in 32bit mode successfully, but I wasn’t attentive and I did not see the Message on the very top left corner of the screen.
