### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by AI-Ying** [cfenollosa/os-tutorial#17]
Hi, I'm a Chinese university student. I got a lot of benefit from your code 'os-tutorial'.It occurred to me that maybe I could translate them to Chinese in recent days.Therefore, I suppose I should ask your permission for the rights of translation.Likewise, I have several understandings on my own, so I'm thinking whether I can add some code lines to your finished codes. I will appreciate it if you allow me to do that. Hoping for your response.  Thanks so much! 谢谢！！

**Comment by cfenollosa** [comment]
Hello, you are free to fork the code and make translations, no permission needed. Thanks for your interest!
