### ISSUE TITLE
14-checkpoint/boot/print_hex.asm : Why add 5 to HEX_OUT?

### ISSUE THREAD

**Issue by VishalDalwadi** [cfenollosa/os-tutorial#170]
I was looking at the assembly file print_hex.asm.
`mov bx, HEX_OUT + 5`
Why add 5 to HEX_OUT, when the string length is 4?
I think it should be
`mov bx, HEX_OUT + 3`

**Comment by farisshajahan** [comment]
@VishalDalwadi It is to account for the 0x in the HEX_OUT string as well.
