### ISSUE TITLE
14-GCC Can't Compile GDB

### ISSUE THREAD

**Issue by pennacap** [cfenollosa/os-tutorial#174]
I am using Ubuntu 20.04 on WSL.

I ran 
`curl -O http://ftp.rediris.es/mirror/GNU/gdb/gdb-7.8.tar.gz`
followed by 
`tar -xf gdb-7.8.tar.gz && mkdir gdb-build && cd gdb-build && export PREFIX="/usr/local/i386elfgcc" && export TARGET=i386-elf && ../gdb-7.8/configure --target="$TARGET" --prefix="$PREFIX" --program-prefix=i386-elf- && make && sudo make install `

but its giving me
```
make[5]: Entering directory '/home/pennacap/bestos/tmp/src/gdb-build/bfd'         
make[5]: Nothing to be done for 'install-exec-am'.
test -z "" || /usr/bin/mkdir -p ""     
test -z "" || /usr/bin/mkdir -p ""                                                               
make[5]: Leaving directory '/home/pennacap/tmp/src/gdb-build/bfd'                         
make[4]: Leaving directory '/home/pennacap/tmp/src/gdb-build/bfd'                        
make[3]: *** [Makefile:1652: install-recursive] Error 1                                          
make[3]: Leaving directory '/home/pennacap/tmp/src/gdb-build/bfd'                         
make[2]: *** [Makefile:1789: install] Error 2                                                    
make[2]: Leaving directory '/home/pennacap/tmp/src/gdb-build/bfd'                         
make[1]: *** [Makefile:2664: install-bfd] Error 2                                                
make[1]: Leaving directory '/home/pennacap/tmp/src/gdb-build'                             
make: *** [Makefile:2153: install] Error 2             
```

What should I do?

**Comment by Mitgorakh** [comment]
I had the same exact same issue. Somehow doing everything in the gdb-7.8 folder instead of the gdb-build folder fixed the issue. Still no idea what caused it or what fixed it though.

**Comment by FreddyJS** [comment]
I had the same issue on a Ubuntu 20.04.
In my case i didn't have the library termcap installed. Installing libncurses5-dev and texinfo fixed my problem (dont know if texinfo is needed).  
`sudo apt-get install libncurses5-dev texinfo`

**Comment by pennacap** [comment]
> I had the same exact issue. Somehow doing everything in the gdb-7.8 folder instead of the gdb-build folder fixed the issue. Still no idea what caused it or what fixed it though.

This worked for me. 
Thanks

**Comment by pennacap** [comment]
> I had the same issue on a Ubuntu 20.04.
> In my case i didn't have the library termcap installed. Installing libncurses5-dev and texinfo fixed my problem (dont know if texinfo is needed).
> `sudo apt-get install libncurses5-dev texinfo`

I h
