### ISSUE TITLE
13-kernel-barebones - Can't read kernel from floppy image

### ISSUE THREAD

**Issue by yuukidesu9** [cfenollosa/os-tutorial#177]
Good afternoon, friends.
Well, I set up everything here: GCC cross-compiler, NASM and an emulator (Bochs). But I can't seem to boot the kernel in protected mode in any way!
I double- (and triple-) checked the code for errors, even compiled it manually step by step, but it seems all fine!
I put some messages for visual debugging purposes, and here's the thing:
- First, it says that switches to 16-bit real mode.
- Then, it says that's loading the kernel. And stays there.
- In the Bochs console, it shows the floppy has read 0 sectors, almost as if there's nothing there!
So, any ideas of what it can be?

**Comment by algorithmx51** [comment]
have you tried executing your kernel with qemu? 
Maybe you set something wrong in the bochs configuration file or there is a bug on the config of the tutorial. 
qemu does this automatically.

**Comment by yuukidesu9** [comment]
Same thing on QEMU. It stalls before loading the kernel to memory.
I even pushed the [current code](https://github.com/yuukidesu9/yuuos/) if you want to take a look.

**Comment by algorithmx51** [comment]
I am going to take a look in your code and let you know if I figure out what is wrong

**Comment by algorithmx51** [comment]
Ok so i found what is wrong
In 32bit-switch you have :
`switch_protmode:

    ; First things first: no interrupts
    cli
    ; Load our GDT descriptor.
    lgdt [gdt_descriptor]
    ; Set 32-bit mode in CR0 register!
    ; Yay!
    mov eax, cr0
    or eax, 0x1
    ; And jump to our code segment!
    jmp CODE_SEG
    call init_pm`

The correct code :

`switch_protmode:

    ; First things first: no interrupts
    cli
    ; Load our GDT descriptor.
    lgdt [gdt_descriptor]
    ; Set 32-bit mode in CR0 register!
    ; Yay!
    mov eax, cr0
    or eax, 0x1
    mov cr0, eax ; LOAD cr0 to notify the processor
    ; And jump to our code segment!
    jmp CODE_SEG:init_pm ; do a FAR jump in the CODE_SEG`

Also, remove the `jc disk_error` and `jne sectors_error,` since you will never have a perfect size for your OS, so it is ok if the ir an error :

`; Time to pop those stuff open!
disk_load:

    pusha
    push dx
    ; The AH register stores the function
    ; used in interrupt 0x13.
    ; In this case, 002 means 'read'.
    mov ah, 0x02
    ; The AL register stores the number
    ; of sectors to read (0x01 to 0x80).
    ; In this case, it's using DH's value,
    ; which is 2 (0x02) sectors.
    mov al, dh
    ; The CL register stores where we
    ; can start reading the disk.
    ; In this case, the second (0x02)
    ; sector.
    mov cl, 0x02
    ; The CH register stores the number
    ; of the cylinder (0x00 to 0x3FF).
    ; In this case, it's the first one,
    ; so it's 0 (0x00).
    mov ch, 0x00
    ; The DH register stores which head
    ; we will use (0x00 to 0x0F).
    ; In our case, it's the first one
    ; (0x00).
    mov dh, 0x00
    ; Call the interrupt and read!
    int 0x13
    ; In case of error...

    ;jc disk_error <- comment
    ; ...but if there's no errors...

    pop dx
    ; Compare the number of sectors read.
    cmp al, dh
    ; And in case of errors...
    ;jne sectors_error <- comment
    ; ...if no errors...
    popa
    ; ...we stop.
    ret
`

**Comment by yuukidesu9** [comment]
It worked! Thanks a lot!
