### ISSUE TITLE
It is not possible to find a positional parameter that accepts the 'kernel.bin' argument.

### ISSUE THREAD

**Issue by ShintaroBRL** [cfenollosa/os-tutorial#178]
command:
`cat bootsect.bin kernel.bin > os-image.bin`

Error:
```
Get-Content : It is not possible to find a positional parameter that accepts the 'kernel.bin' argument.
No linha:1 caractere:1
+ cat bootsect.bin kernel.bin > os-image.bin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

How do I solve this?

I'm on a win 10 64Bits computer, installed everything to get here and stopped this error that I don't know how to solve

**Comment by algorithmx51** [comment]
cat command is for linux , use copy /b param1+param2 output


Στις Σάβ, 12 Σεπ 2020, 01:16 ο χρήστης Juliano Lira <
notifications@github.com> έγραψε:
