### ISSUE TITLE
I don't see any reasons in the README why it was ever done

### ISSUE THREAD

**Issue by ponyatov** [cfenollosa/os-tutorial#179]
Good day

I don't see any reasons in the README why it was ever done.

* Why write a new OS?
* Why write bootloader when we already have the `syslinux`, `GRUB`, and `u-boot` at least?
* Why should we ever think about writing bare-metal core, while there is a huge amount of unsolved problems such as distributed systems? We can experiment with using guest OS approach: just run generic executable modules thinking about them as OS kernels.

**Comment by ponyatov** [comment]
Really, why not use the guest OS approach? Any modern general-purpose OS has the ability to run programs in hypervisor modes. On the other side, OS can be thought of as a generalized part of multiple bare-metal programs, which was selected as a separate component. The same way we can take multiple programs for mainstream OSes, select some shared part of its logic, and implement it as an isolated guest OS.

**Comment by ponyatov** [comment]
Another approach: write not an OS, but a metaOS -- as a model of all possible OSes design, implement it by inheriting from the base minimal possible design to more complex components. It can be done even in Python -- create classes of OS components, which able to translate itself into parts of C source code. If you want to build your own OS, you can take that metaOS library, inherit components and modify them as you want, then combine into a project, and call this project compilation methods.

**Comment by algorithmx51** [comment]
This os development tutorial is a tutorial not only in how to write an OS, but how to write a bootloader, how to boot in 32-bit mode (maybe we will load in 64-bit long mode too in the future), and then how to write an OS.
It is written for programmers that start now thier course on OSdev, and so they do not have to read a already huge amount of source code from other OS that even have a GUI. It is simple, small, and probably will handle the basics that an OS does, like networking, paging, multithreading and multitasking. Don't forget that this project is on development and it is actually a hoby of the creator.
