### ISSUE TITLE
How can I build the object files in a different directory?

### ISSUE THREAD

**Issue by JavaMatia** [cfenollosa/os-tutorial#183]
I managed somehow to do so, but my make file looks discussing and super messy. If anyone has a clean way and can explain how to do it, I'll appreciate it very much.

Thanks!

**Comment by algorithmx51** [comment]
change %.o to e.g. obj/%.o

**Comment by JavaMatia** [comment]
I spent three hours trying to figure this out... Thanks!

**Comment by JavaMatia** [comment]
Anyway to create to target folders automatically?

**Comment by algorithmx51** [comment]
the same way, change any .x files to test_folder/%.x to target them in a specific directory

**Comment by JavaMatia** [comment]
I meant if the "test folder" and its subdirectories don't exist, it results an error. So I have to manually create the folders. For example: obj/kernel obj/drivers obj/libc and so on. If these folders don't exist, it just won't work. Is there a way to force create these directories if they don't exist?

**Comment by algorithmx51** [comment]
oh now i understand

add this

    rm -rf obj/
    mkdir obj
    mkdir obj/kernel
    mkdir obj/drivers
    etc.

before the `build:` in the make file

Also, add this routine
    clean:
        rm -rf obj/

**Comment by JavaMatia** [comment]
That's exactly what I did, but if I create new folders I have to edit the make file to create the folders. Isn't there a better way to automatically create newly created source folders? For example if I decide to add kernel/screen directory, I need to add to the clean method `mkdir -p obj/kernel/screen`, it just seem not right...

**Comment by algorithmx51** [comment]
i have an idea. is your source directory the same with your obj directory?
if yes, then you can copy the src directory to the obj and delete the files

**Comment by JavaMatia** [comment]
thanks
