### ISSUE TITLE
multiple definition of idt; idt.h: first defined here

### ISSUE THREAD

**Issue by nikhilAnayak** [cfenollosa/os-tutorial#194]
Hi. I'm currently working on lesson 19. I finished, but when I compile, I get this error. I have the include guards so I don't know why this is happening, but it also happens os the os-tutorial code when I clone, make, and run it. I'm not sure how to proceed.

**Comment by ryansnewell** [comment]
Which version of GCC are you using? I was having the same issue and found out that in gcc-10 they changed a default behavior that caused this issue. To fix it I had to add the -fcommon flag. Hope this helps

**Comment by nikhilAnayak** [comment]
Sorry, I forgot about this issue I opened but I solved this problem. I don't exactly remember how but I just messed around with some of the variables and removes repeating variables. I will be closing the issue because I don't this there's any problem I have.
