### ISSUE TITLE
Can't install gdb-7.8

### ISSUE THREAD

**Issue by BaseProgrammer** [cfenollosa/os-tutorial#196]
So I've hopped onto chapter 14, just a side note, everything worked before chapter 14, and I was trying to install gdb but when I ran `sudo make install` or just `sudo make` in general, I get so many errors like "make: *** [Makefile:2153: install] Error 2" and much more.

So I also wanted to run the code on chapters 15 and 16 but on chapter 15 I get errors/warnings saying that the file "ports.h" has undefined references (sorry I don't know much with the GCC C-lang compiler, I am running GCC-8). This also shows with the screen.h file on chapter 16; I get errors like...
```
/usr/local/i386elfgcc/bin/i386-elf-ld: warning: cannot find entry symbol _start; defaulting to 0000000000001000
bin/kernel.o: In function `main':
kernel.c:(.text+0x12): undefined reference to `clear_screen'
kernel.c:(.text+0x23): undefined reference to `kprint_at'
kernel.c:(.text+0x37): undefined reference to `kprint_at'
kernel.c:(.text+0x4b): undefined reference to `kprint_at'
kernel.c:(.text+0x5b): undefined reference to `kprint'
kernel.c:(.text+0x6f): undefined reference to `kprint_at'
```
This shows when I try to run `sudo ${ld} -o bin/kernel.bin -Ttext 0x1000 bin/kernel_entry.o bin/kernel.o --oformat binary` (to make the kernel.bin file), and there is no "kernel.bin" file in the bin/ directory.

I probably think I am running the commands wrong since there aren't issues with this topic. Any solutions are appreciated, thanks.

**Comment by BaseProgrammer** [comment]
![image](https://user-images.githubusercontent.com/74561974/109357837-c61c0380-787a-11eb-9dd1-54d961d03aa0.png)
This is how my files look like; it's not on my latest GitHub repo yet since there's errors.

**Comment by leysdun041** [comment]
You haven't compiled the screen.c and ports.c files. First compile those files and add it to the link command.

**Comment by BaseProgrammer** [comment]
Oh alright, thanks!

**Comment by BaseProgrammer** [comment]
@leysdun041 I can't my `screen.c` file nor the `ports.c` file...
Error for ports.c file:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```
I compiled this by doing "gcc ports.c -o ports"
Same for the screen.c file...
```
screen.c: In function ‘clear_screen’:
screen.h:1:23: warning: initialization of ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 #define VIDEO_ADDRESS 0xb8000
                       ^~~~~~~
screen.c:97:20: note: in expansion of macro ‘VIDEO_ADDRESS’
     char *screen = VIDEO_ADDRESS;
                    ^~~~~~~~~~~~~
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
/usr/bin/ld: /tmp/ccv6OZY3.o: in function `get_cursor_offset':
screen.c:(.text+0x1f2): undefined reference to `port_byte_out'
/usr/bin/ld: screen.c:(.text+0x1fc): undefined reference to `port_byte_in'
/usr/bin/ld: screen.c:(.text+0x214): undefined reference to `port_byte_out'
/usr/bin/ld: screen.c:(.text+0x21e): undefined reference to `port_byte_in'
/usr/bin/ld: /tmp/ccv6OZY3.o: in function `set_cursor_offset':
screen.c:(.text+0x254): undefined reference to `port_byte_out'
/usr/bin/ld: screen.c:(.text+0x269): undefined reference to `port_byte_out'
/usr/bin/ld: screen.c:(.text+0x278): undefined reference to `port_byte_out'
/usr/bin/ld: screen.c:(.text+0x28a): undefined reference to `port_byte_out'
collect2: error: ld returned 1 exit status```

**Comment by BaseProgrammer** [comment]
OMG! I got it to work, I feel so stupid. I just ran `make kernel.bin` to make it work.

**Comment by BaseProgrammer** [comment]
I got it to work but I'm not sure how to add the `ports.o`, `screen.o` file and merge it with the `kernel.o` file to make it into a `kernel.bin` file; can you send me a command/way to do so; Thanks @leysdun041

**Comment by leysdun041** [comment]
You link the object files to create the executable. According to the makefile the command is 
${ld} -o kernel.bin -Ttext 0x1000 --oformat binary bin/kernel_entry.o bin/kernel.o bin/ports.o bin/screen.o 
With the link command you just list the object files you want to link together. In the makefile you would use a list of the files. Also ld will be the linker that you are using for the project. I think this is discussed in section 11 of the tutorial.

**Comment by BaseProgrammer** [comment]
Oh cool, thanks A LOT!
