### ISSUE TITLE
Nothing gets printed on QEMU

### ISSUE THREAD

**Issue by BaseProgrammer** [cfenollosa/os-tutorial#197]
On Chapter/Lesson 16, it had a function in the kernel where it printed text on the screen; I'm not sure if it works for others but when I used QEMU to run the BIN file, nothing got printed but the screen did get cleared. 

After a while of trying to re-run the bin file, it says...
```
Unable to init server: Could not connect: Connection refused
WARNING: Image format was not specified for 'drippleos.bin' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
gtk initialization failed```

**Comment by BaseProgrammer** [comment]
I have then moved on to the next lesson, which works but there is no

**Comment by Arnau478** [comment]
Have you found any solution? I am now with that bug...
