### ISSUE TITLE
15 - Boot looping

### ISSUE THREAD

**Issue by BetaPictoris** [cfenollosa/os-tutorial#206]
When I am building the OS on `15-video-ports` I get an error in my terminal that says. 

```
./src/kernel.c:29:17: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
     char *vga = 0xb8000;
                 ^~~~~~~
```

QEMU ends up just looking like it is boot looping. 

Repo: [MrHallway0/Tea](https://github.com/mrhallway0/tea).

**Comment by MrHallway0** [comment]
![Screenshot from 2021-05-17 23-14-48](https://user-images.githubusercontent.com/65696362/118584846-c59e5500-b765-11eb-80a6-4e886680c89e.png)

**Comment by ltgr** [comment]
I had this same problem, did you end up fixing it?

**Comment by MrHallway0** [comment]
> I had this same problem, did you end up fixing it?

To be honest I haven't, yet, I think it is something wrong with the code, I was going to test it soon.

**Comment by ltgr** [comment]
Issue #44 looks promising, but I haven't gotten it working yet

**Comment by ltgr** [comment]
Deleting the clear_screen() function call in main() seemed to stop the flickering/rebooting, so I'm going to assume the problem has to do with that

**Comment by ltgr** [comment]
Nevermind, the clear_screen didn't seem to be the problem. The clear screen code runs but kprint_at don't display anything on the screen, and qemu is stuck on the "Loaded 32-bit protected mode" screen. I was able to figure out that the problem is with the kprint function, as kprint_at doesn't break anything(but still doesn't work) while kprint() causes the constant rebooting

**Comment by BetaPictoris** [comment]
Sorry for the late reply, but my issue was that I wasn't building the files needed. 
Here is the code: https://github.com/BetaPictoris/Tea.

The issue seemed to come from the fact that my build file looked like this:
```
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-gcc -ffreestanding -c ./src/kernel.c -o ./bld/kernel.o
nasm ./src/kernel_entry.asm -f elf -o ./bld/kernel_entry.o
nasm ./src/cpu/interrupt.asm -f elf -o ./bld/interrupt.o
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-ld -o ./bld/kernel.bin -Ttext 0x1000 ./bld/kernel_entry.o ./bld/kernel.o --oformat binary
```

and not this:
```
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-gcc -c ./src/kernel/util.c -o ./bld/util.o
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-gcc -c ./src/cpu/idt.c -o ./bld/idt.o 
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-gcc -c ./src/cpu/isr.c -o ./bld/isr.o
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-gcc -c ./src/drivers/screen/screen.c -o ./bld/screen.o
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-gcc -c ./src/drivers/ports/ports.c -o ./bld/ports.o
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-gcc -ffreestanding -c ./src/kernel.c -o ./bld/kernel.o
nasm ./src/kernel_entry.asm -f elf -o ./bld/kernel_entry.o
nasm ./src/cpu/interrupt.asm -f elf -o ./bld/interrupt.o
./scripts/i386-elf-7.5.0-Linux-x86_64/bin/i386-elf-ld -o ./bld/kernel.bin -Ttext 0x1000 ./bld/ports.o ./bld/screen.o ./bld/interrupt.o ./bld/util.o ./bld/idt.o ./bld/isr.o ./bld/kernel_entry.o ./bld/kernel.o --oformat binary
```
