### ISSUE TITLE
10-32bit-enter code not working

### ISSUE THREAD

**Issue by Aatmik211** [cfenollosa/os-tutorial#207]
When I am running the code for 32bit-main.asm from chapter 10, the code just keeps looping infinitely without displaying anything. I cross-checked my code and everything is the same. Can someone explain/help me solve this issue?

**Comment by Aatmik211** [comment]
Ok, so I am closing this post since I fixed the problem and now my OS is booting into proteccted mode correctly.

**Comment by Lioncat2002** [comment]
> Ok, so I am closing this post since I fixed the problem and now my OS is booting into proteccted mode correctly.
@Aatmik211 
Hey um I am facing the same problem can you please explain what did you do?

**Comment by illegitimate-egg** [comment]
How did you fix it

**Comment by gavin0727** [comment]
> How did you fix it

dont use this option `-nographic`
