### ISSUE TITLE
13 - Kernel Barebones (kernel "X" doesn't get printed)

### ISSUE THREAD

**Issue by tarithj** [cfenollosa/os-tutorial#208]
[boot.zip](https://github.com/cfenollosa/os-tutorial/files/6506927/boot.zip)
![image](https://user-images.githubusercontent.com/29999281/118777806-18335a80-b8a7-11eb-9fc5-a41066fb0adf.png)
The kernel doesn't print "X" and the "The loading kernel to memory" is missing some characters

**Comment by tarithj** [comment]
I fixed it by using --curses flag when running qemu

**Comment by vinsdragonis** [comment]
> I fixed it by using --curses flag when running qemu

I tried this but to no avail. It still gets stuck with the same message displayed.

**Comment by RhysFonville** [comment]
Same here. Not sure what I did wrong.

**Comment by firestar4204** [comment]
Make sure you are not using the --nographic flag.  VGA (which is being used to print the X) is graphical.

**Comment by RhysFonville** [comment]
I had the same problem. Turns out I just didn't update my bootloader code from the last lesson.
