### ISSUE TITLE
M1 Mac qemu?

### ISSUE THREAD

**Issue by mjkpolo** [cfenollosa/os-tutorial#212]
I have struggled to find a way to run these raw images in qemu on the m1 mac. I resorted to running qemu inside an Ubuntu VM using UTM, which also uses qemu. So it does work but only inside my arm Linux VM... has anyone figured out how to get this to work? I just get an error saying cannot allocate memory buffer. (I am trying qemu-system-x86) Thanks!!!!

**Comment by MrHallway0** [comment]
It should work... I used QEMU on an ARM Chromebook. You could try [this](https://github.com/AkihiroSuda/lima).

**Comment by mjkpolo** [comment]
> It should work... I used QEMU on an ARM Chromebook. You could try [this](https://github.com/AkihiroSuda/lima).

I'm confused, is this better/different than docker? And do you mean I can run qemu through this? Cuz that's nested qemu like I'm doing now right?

**Comment by MrHallway0** [comment]
I haven't personally used it, I use Windows at the moment. But it is built for Macs so it should preform better then your current setup. You could also try building QEMU for ARM on Mac OS and see if it solves your problems.

**Comment by mjkpolo** [comment]
Ah gotcha. I did try building from source with different versions and patches too, but maybe I haven't tried the right one. Currently using the homebrew build. Thanks! If someone has a guide that works lmk

**Comment by mjkpolo** [comment]
Yay so I figured it out. It's one of or both of two things. I used [this](https://github.com/knazarov/homebrew-qemu-virgl) brew to get qemu and I also disabled system integrity protection in recovery mode terminal! So there, if anyone wants  to use this on the m1, do the following!!!
