### ISSUE TITLE
Some of the tutorials expect you to copy and paste code

### ISSUE THREAD

**Issue by Shadowblitz16** [cfenollosa/os-tutorial#215]
Some of the tutorials don't go into full detail where things should be and expect you to look at the provided source files and copy and paste them.

one of the tutorials I am talking about is the 03 memory one.
it doesn't really explain or tell you where to put the code relative to what you have already.

consider telling people your expanding on a previous tutorial or creating a new file and using `...` to signal users the beginning and end of existing code as well as putting in comment the file you are working on.

example...
`<new file or expanding on existing one>`
```
//<the current file>.<the current exension>

...
<previous line of existing code>
<new code> //comment explaining what it does
...

```

**Comment by TopchetoEU** [comment]
I think the author of this repo has long forgotten about this tutorial, it's a waste of time to log issues here

**Comment by Shadowblitz16** [comment]
:c
