### ISSUE TITLE
17-video-scroll + 18-interrupts Issues

### ISSUE THREAD

**Issue by patrick-media** [cfenollosa/os-tutorial#228]
Initially, I attempted lesson 17-video-scroll, when I came across issues. I could get the image to boot in QEMU, though it would stop after landing in 32-bit PM, and wouldn't continue. I looked at the number of sectors to pass to disk_load in my bootsector, and they were okay, though I did notice that my lesson 16 os-image was 10 MB, where my lesson 17 os-image was only just above 2 MB. I wonder if I'm linking them correctly or not. I am not using a Makefile and am just typing the commands manually, which does lead to typos, but I cannot get Makefiles to work properly for some strange reason. I have also tried commenting out certain portions of kernel.c wondering if it's a specific function dragging it down, but to no avail.

I decided to move on to lesson 18, assuming it was just something I couldn't fix that might work next time (I am tremendously foolish). This time the linker cries about multiple definitions of "idt" and "idt_reg" instances in my "isr.o" file, with the initial definition in "idt.o". Before, the duplicate was in "idt.o" and the initial definition was in "kernel.o", so I am not at all sure what is going on. It is definitely something to do with linking them. I have triple checked the header guards to make sure there isn't anything wrong. I will gladly provide the source if needed, though I hope this can be solved with a linker amendment or fix. I am using the GCC compile flags and the LD flags designated [here](https://github.com/cfenollosa/os-tutorial/pull/180/commits/e867d6742d54ea4543247a1e2477f5c39925e832). Shall I recompile my build tools? Perhaps there is a new version of them, or maybe something is wrong in my scripts. The fix to 17 may subsequently lead to 18 working as well. I have no idea and I would appreciate some input from someone that is probably better than I am in this department. Thank you in advance.

**Comment by wantyapps** [comment]
I have this issue too
<img width="1440" alt="Screen Shot 2022-01-21 at 13 04 01" src="https://user-images.githubusercontent.com/56798701/150516394-8f3256c8-84ba-4a73-8988-fb657ea567cd.png">
!

**Comment by xing1357** [comment]
Try `--allow-multiple-definition` for the linker.

**Comment by patrick-media** [comment]
Thank you very much for the help. This solved my current issue.
