### ISSUE TITLE
bootloader freezes at loading kernel into memory on dell optiplex 790

### ISSUE THREAD

**Issue by 404Dev-404** [cfenollosa/os-tutorial#230]
i think it might be because the code has some problems on the dell pc or it's just incredibly slow and i expect it to be faster because i've run it on qemu all of the time

**Comment by Seanld** [comment]
What does your boot sector assembly look like?

**Comment by 404Dev-404** [comment]
https://github.com/404Dev-404/lychee/blob/main/boot/bootsect.asm

**Comment by Menotdan** [comment]
> or it's just incredibly slow and i expect it to be faster because i've run it on qemu all of the time

def not this, otherwise it would load other, bigger OSes in so long (like over an hour at least)

**Comment by Seanld** [comment]
Is this happening when you're booting it on bare metal, or through a VM? If on bare metal, I recall seeing somewhere that reading too many sectors at once caused some problems for someone. You're reading 54, which _is_ quite a few. If your kernel code isn't too large, maybe try reducing the sectors down to only what is necessary, and see if that changes things?
