### ISSUE TITLE
Lesson 11: Cannot get the prefix | Linux

### ISSUE THREAD

**Issue by Pigiotyreal** [cfenollosa/os-tutorial#233]
Hi! I am on ubuntu linux, and I am having trouble getting the prefix from lesson 11 onto my system, can someone help me?

**Comment by Dennis-Johnson** [comment]
```export PREFIX="/usr/local/i386elfgcc"```

This is the path to the GCC that you're going to build in the following steps will be installed. That directory wouldn't exist by default in ```/usr/local/```.

**Comment by Pigiotyreal** [comment]
I have gcc preinstalled, so how do I get it there

**Comment by Pigiotyreal** [comment]
thanks
