### ISSUE TITLE
Difference in binary code between the book and my PC

### ISSUE THREAD

**Issue by highonweb** [cfenollosa/os-tutorial#250]
The binary resulting from assembly code is different from what is given in the book.

Is this Normal?

Why does this Happen ?

**Comment by RedLeader167** [comment]
> The binary resulting from assembly code is different from what is given in the book.
> 
> Is this Normal?
> 
> Why does this Happen ?

Different compilers and versions of compilers can output different code

**Comment by highonweb** [comment]
Thanks
