### ISSUE TITLE
Result displayed on the terminal itself

### ISSUE THREAD

**Issue by Deehan1866** [cfenollosa/os-tutorial#259]
I am using WSL ubuntu on windows...
After running the .bin file the result is showing in the terminal. If i want to run another .bin file i have to cancel the terminal which is quite ridiculous..

How can i show my result in qemu emulator?!?!

**Comment by ilyascodes24** [comment]
Do you have any GUI for WSL?
If not, follow the instructions at this link: [https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#4-configure-ubuntu](url)
