### ISSUE TITLE
How we can boot it on a real machine?

### ISSUE THREAD

**Issue by horechek** [cfenollosa/os-tutorial#3]
Perhaps create a bootable USB flash drive?

**Comment by CliffracerX** [comment]
As far as I can tell, the latest version of Linux Mint can write the produced os-image.bin to a hard-drive, so if you spin up a VM of it and give it a USB stick to make bootable, you should be able to use the "Disk Image Writer" tool to write it to the USB stick, then boot off of it.

Take this with a grain of salt however, I've only done this with VMs and VHD files.

**Comment by cfenollosa** [comment]
Added a wiki page with the solution: https://github.com/cfenollosa/os-tutorial/wiki/How-to-boot-on-a-real-machine

**Comment by 0xqookie** [comment]
You can always write the os-image.bin to a floppy disk using a external disk drive. That is what I did with my os
