### ISSUE TITLE
01-bootsector-barebones issue - expecting raw image?

### ISSUE THREAD

**Issue by ariisboss** [cfenollosa/os-tutorial#32]
`qemu-system-x86_64 boot_sect_simple.bin
WARNING: Image format was not specified for 'boot_sect_simple.bin' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Could not initialize SDL(No available video device) - exiting`
I receive this error when attempting to run the basic bootsector. Is there something I have to specify?

**Comment by teaguejt** [comment]
Does it run? If so, that’s normal. Mine does that as well, but it works just fine. I think it’s just a QEMU thing, and since there’s no “established” format for these .bin files it’s not an error that can be cleared up. Try providing the —format=raw (or whatever it is) flag to suppress the warning.

**Comment by teaguejt** [comment]
As for the SDL error, someone else will have to comment on that. I’m not familiar with it. What system are you running on? Linux?

**Comment by ariisboss** [comment]
I am running Ubuntu 16.04 on WSL (Windows Subsystem for Linux) - Windows 10 Build 16299. I don't believe that WSL is the problem. The program does not run. It just throws up an error.

**Comment by teaguejt** [comment]
Okay, yeah. The format warning is just a warning, and goes hand in hand with what we’re doing. The SDL error is a little trickier. Try passing the `-curses` or `-nographic` flag(s) to QEMU. That might help.

**Comment by ariisboss** [comment]
Leaving both `-nographic` and `-curses` flags worked! No errors or warnings were given! Thank you!

**Comment by sytranvn** [comment]
How can you stop the infinite loop? I ran  it on Ubuntu and couldn't stop it by Ctrl+C.
