### ISSUE TITLE
flickering screen - lesson 10

### ISSUE THREAD

**Issue by KonstantinosGiannakakis** [cfenollosa/os-tutorial#34]
Hello,

When i am running 32bit_main in qemu, in lesson 10, is not working properly.
The screen is flickering, like is constantly rebooting. This only happens when i got 32 bit enabled.
When i comment out all 32bit code, and keep only 16bit is working properly.. any fixes for that?
I am sure that the problem is something about 32bit, but dont know exactly what.

**Comment by Ghifari160** [comment]
I followed the lesson and it worked. If you post your code, I can try to help find the problems..

**Comment by KonstantinosGiannakakis** [comment]
Fixed it!
i just messed up with the flags of gdt_data!
