### ISSUE TITLE
404 error while fetching GDB sources

### ISSUE THREAD

**Issue by raibu** [cfenollosa/os-tutorial#37]
Change the link in 14 lesson README to `http://ftp.rediris.es/mirror/GNU/gdb/gdb-7.8.tar.gz` because of 404 error

**Comment by Ghifari160** [comment]
@raibu I made a pull request that reflects that change. Now we just have to wait for @cfenollosa to approve and merge it.

**Comment by cfenollosa** [comment]
Thanks to both of you for reporting and fixing the issue!
