### ISSUE TITLE
Problem in running the kernel - lesson 13

### ISSUE THREAD

**Issue by ChanderG** [cfenollosa/os-tutorial#4]
First of all, thanks for this awesome tutorial.

I am having problems in the 13th lesson. The qemu screen just flickers. By placing some jmp $ here and there, I find that everything is fine untill the "call KERNEL_OFFSET" in BEGIN_PM in the bootsect.asm.That is control never reaches the first line of kernel_entry.asm.

There are no disk read errors (using fda) and no trouble in reaching 32 bit protected mode. Any ideas?

How exactly do I verify that the kernel binary is placed at 0x1000? Both ndisasm and xxd do not seem to show this.

**Comment by ChanderG** [comment]
By the way, I am on an Ubuntu 12.04 machine. 
QEMU emulator version 1.0 (qemu-kvm-1.0)
NASM version 2.09.10
Cross compiled gcc exactly as prescribed.

**Comment by cfenollosa** [comment]
Hi ChanderG:

I just tried compiling and running it:
```
$ make run
i386-elf-gcc -ffreestanding -c kernel.c -o kernel.o
i386-elf-ld -o kernel.bin -Ttext 0x1000 kernel_entry.o kernel.o --oformat binary
i386-elf-ld: warning: cannot find entry symbol _start; defaulting to 0000000000001000
cat bootsect.bin kernel.bin > os-image.bin
qemu-system-i386 -fda os-image.bin
```

As you see, the 0x1000 is pretty much the default. Please make sure that you're using the correct syntax for your version of `ld`.

I'd suggest trying to set breakpoints in kernel.c to see if it's really jumping into it, or modify `bootsect.asm` to print `KERNEL_OFFSET` just before jumping into it, and check that it's really 0x1000

"Screen flickering" looks like the CPU is triple faulting and restarting over and over again. You can check that by using the qemu flag `-d guest_errors,int` and looking for a triple kernel panic-like dump.

Debugging this is pretty hard, I know. Good luck!

**Comment by firestar115** [comment]
After trying to print KERNEL_OFFSET, It gave me 0x0000 (using print_hex)

This is the first few lines of my `boot.asm`:

    [org 0x7c00]
    KERNEL_OFFSET equ 0x1000
    
    mov bx, KERNEL_OFFSET
    call print_hex
    call println
    jmp $

What is going wrong?

**Comment by firestar115** [comment]
When looking at my `os-image.bin` in `xxd`, I can see that it only goes up to offset 0x00000270. When looking at `kernel.bin` the same way, it is placed at 0x00000200 in `os-image.bin`. I'm going to change KERNEL_OFFSET to see if that helps.

**Comment by firestar115** [comment]
Now the system hangs after printing "loading kernel into memory."

**Comment by cfenollosa** [comment]
Hi firestar115, thanks for your comment.

Unfortunately this is not the right place to discuss problems with your code, but rather to open issues related to the github project.

I'd suggest writing on the [osdev forum](http://forum.osdev.org) where they will help you understand what's going on.

Regards,
Carlos
