### ISSUE TITLE
How to boot?

### ISSUE THREAD

**Issue by Menotdan** [cfenollosa/os-tutorial#52]
I have a usb with os-image.bin on it and it wont boot from physicall machine

**Comment by mohe2015** [comment]
I don't know but it may work if you use dd. 

dd bs=4M if=os-image.bin of=/dev/sdX conv=fsync

replace /dev/sdX with the path to your usb drive. **TAKE CARE TO CHOOSE THE CORRECT DEVICE. OTHERWISE YOU MAY OVERWRITE IMPORTANT DATA**

**Comment by asm-pas** [comment]
I wouldn't suggest that at all, a better way is to install quemo, and run:

> nasm -fbin boot_sect_org.asm -o boot_sect_org.bin
> qemu-system-x86_64 -fda boot_sect_org.bin

**Comment by Menotdan** [comment]
> I wouldn't suggest that at all, a better way is to install quemo, and run:
> 
> `~$nasm -fbin boot_sect_org.asm -o boot_sect_org.bin`
> `~$qemu-system-x86_64 -fda boot_sect_org.bin`

Ya im using that i just want to boot it on usb

**Comment by Menotdan** [comment]
> I don't know but it may work if you use dd.
> 
> dd bs=4M if=os-image.bin of=/dev/sdX conv=fsync
> 
> replace /dev/sdX with the path to your usb drive. **TAKE CARE TO CHOOSE THE CORRECT DEVICE. OTHERWISE YOU WILL OVERWRITE IMPORTANT DATA. /dev/sda WOULD BE DEFINITELY WRONG AS IT IS YOUR CURRENT HARD DRIVE**

Thats wat i did it didnt boot on a physical machine

**Comment by mohe2015** [comment]
I can't try it currently. Did you choose the correct device in the bios menu?

**Comment by Menotdan** [comment]
Yes, when i boot on physicall pc from the usb, it shows a blinking bar/cursor which goes down one line then it just stops

**Comment by Menotdan** [comment]
> I can't try it currently. Did you choose the correct device in the bios menu? And what happens if you try to boot from usb?

I can also boot the usb from qemu

**Comment by Menotdan** [comment]
Here is my code, I update it daily: https://github.com/Menotdan/DripOS How would I make this an iso?

**Comment by MylesJohnson** [comment]
There is this, https://github.com/cfenollosa/os-tutorial/wiki/How-to-boot-on-a-real-machine

**Comment by ice-bit** [comment]
> There is this, https://github.com/cfenollosa/os-tutorial/wiki/How-to-boot-on-a-real-machine

The problem with this solution is that keyboard doesn't work. It seems like a problem with GRUB...

**Comment by PixleProgrambetaxl** [comment]
+1
