### ISSUE TITLE
getting error while installing binutils

### ISSUE THREAD

**Issue by bhavayAnand9** [cfenollosa/os-tutorial#72]
`../binutils-2.24/configure --target=$TARGET --enable-interwork --enable-multilib --disable-nls --disable-werror --prefix=$PREFIX 2>&1 | tee configure.log
`

on executing above command I'm getting these errors. what am I doing wrong ?

checking build system type... i386-apple-darwin17.4.0
checking host system type... i386-apple-darwin17.4.0
checking target system type... i386-pc-elf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking for gcc... /usr/local/bin/gcc-4.9
checking for C compiler default output file name... 
configure: error: in '/tmp/src/binutils-build':
configure: error: C compiler cannot create executables
See config.log' for more details.

**Comment by Ghifari160** [comment]
Are you on macOS? Also can you post the contents of config.log?

**Comment by Auxilus** [comment]
adding sudo solved this for me

**Comment by yizreel-Chen** [comment]
> adding sudo solved this for me

Thx, It works!!!
