### ISSUE TITLE
I have to have this here, right?

### ISSUE THREAD

**Issue by Menotdan** [cfenollosa/os-tutorial#88]
I'm pretty sure I have to have this here, right?
https://github.com/Menotdan/DripOS/blob/master/LICENSE
just double checking, i want to have as little restriction as possible

**Comment by sjx233** [comment]
If your project is a copy of this project with/without modification, you have to include a copy of [this license](https://github.com/cfenollosa/os-tutorial/blob/master/LICENSE) as well.
If not, [the Unlicence](https://unlicense.org/) is probably what you want, or you can choose another one at [Choose a License](https://choosealicense.com/).

**Comment by Menotdan** [comment]
so like, if its a tutorial or would I have to have it for just what I have? Can you double check what I have? I have no idea how it works

**Comment by sjx233** [comment]
Updated my comment above according to what I found in your repository.

**Comment by Menotdan** [comment]
@sjx233 so what I have in my code is ok?

**Comment by sjx233** [comment]
It **is** OK, but your project currently does not have a proper structure. You should move everything from `<repository root>/DripOS` to `<repository root>`. It took me some time to find your actual LICENSE.

**Comment by Menotdan** [comment]
So I can have the Unlicense?

**Comment by sjx233** [comment]
Yes.

**Comment by Menotdan** [comment]
Ok good to know, im closing this now thanks for the help @sjx233
