### ISSUE TITLE
32Bits Enter

### ISSUE THREAD

**Issue by C0d0Type23** [cfenollosa/os-tutorial#89]
I download the code to check if it was not me that I make a mistake but no the code is not correcte.

In the 32bit-main/gdt/print Idk but its not printing "Loaded 32-bit protected mode".
Can someone help me?

**Comment by C0d0Type23** [comment]
Sorry I was not attentive its a the top of the screen -_-
Someone can delete this?

**Comment by Menotdan** [comment]
well its closed so i prob wont get noticed, thats what closed means

**Comment by C0d0Type23** [comment]
Yeah Thanks

**Comment by Menotdan** [comment]
Hey @C0d0Type23  ca u check out my os? https://github.com/Menotdan/DripOS

**Comment by C0d0Type23** [comment]
Hi @Menotdan I check your DripOS an hour ago :D

**Comment by Menotdan** [comment]
@C0d0Type23 how dd u find it?
Also can u maybe run it? Ill add a new release right now

**Comment by C0d0Type23** [comment]
Ok I will check now

**Comment by C0d0Type23** [comment]
Disk Error 0x0C80

**Comment by Menotdan** [comment]
@C0d0Type23 use the -fda flag

**Comment by C0d0Type23** [comment]
okay

**Comment by Menotdan** [comment]
thx @C0d0Type23

**Comment by Menotdan** [comment]
can u link me that post?

**Comment by Menotdan** [comment]
Also its kinda annoying that they have to act like caps lock

**Comment by C0d0Type23** [comment]
https://github.com/cfenollosa/os-tutorial/issues/88

**Comment by C0d0Type23** [comment]
Yah its annoying

**Comment by Menotdan** [comment]
nice

**Comment by C0d0Type23** [comment]
@Menotdan Do you have discord?

**Comment by Menotdan** [comment]
Yes

**Comment by C0d0Type23** [comment]
Nice can you let me add you as friend?

**Comment by Menotdan** [comment]
whats ur username

**Comment by Menotdan** [comment]
hold on
https://discord.gg/E9ZXZWn

**Comment by C0d0Type23** [comment]
MrWillGamerQc#7749

**Comment by Menotdan** [comment]
there, a discussion server for the OS
