### ISSUE TITLE
Hangs after loading kernel into memory

### ISSUE THREAD

**Issue by Menotdan** [cfenollosa/os-tutorial#90]
My code hangs after loading kernel into memory.
; Identical to lesson 13's boot sector, but the %included files have new paths
[org 0x7c00]
KERNEL_OFFSET equ 0x1000 ; The same one we used when linking the kernel

    mov [BOOT_DRIVE], dl ; Remember that the BIOS sets us the boot drive in 'dl' on boot
    mov bp, 0x9000
    mov sp, bp

    mov bx, MSG_REAL_MODE 
    call print
    call print_nl

    call load_kernel ; read the kernel from disk
    call switch_to_pm ; disable interrupts, load GDT,  etc. Finally jumps to 'BEGIN_PM'
    jmp $ ; Never executed

%include "print.asm"
%include "hexprint.asm"
%include "disk.asm"
%include "32bit-gdt.asm"
%include "32bit-print.asm"
%include "32bit-switch.asm"

[bits 16]
load_kernel:
    mov bx, MSG_LOAD_KERNEL
    call print
    call print_nl

    mov bx, KERNEL_OFFSET ; Read from disk and store in 0x1000
    mov dh, 64 ; Our future kernel will be larger, make this big
    mov dl, [BOOT_DRIVE]
    call disk_load
    ret

[bits 32]
BEGIN_PM:
    mov ebx, MSG_PROT_MODE
    call print_string_pm
    call KERNEL_OFFSET ; Give control to the kernel
    jmp $ ; Stay here when the kernel returns control to us (if ever)

BOOT_DRIVE db 0 ; It is a good idea to store it in memory because 'dl' may get overwritten
MSG_REAL_MODE db "Started in 16-bit Real Mode", 0
MSG_PROT_MODE db "Landed in 32-bit Protected Mode", 0
MSG_LOAD_KERNEL db "Loading kernel into memory", 0

; padding
times 510 - ($-$$) db 0
dw 0xaa55
thats the boot sector

**Comment by Menotdan** [comment]
this is dead now many new updates to os here: https://github.com/Menotdan/DripOS
i have since fixed the issue
please close this i dont know how

**Comment by Menotdan** [comment]
WHat lesson u on @Hurricane996

**Comment by Hurricane996** [comment]
14. any ideas?

**Comment by Menotdan** [comment]
@Hurricane996 Try changing the value in this file on line 31:
https://github.com/cfenollosa/os-tutorial/blob/master/14-checkpoint/boot/bootsect.asm

Make it bigger if anything.
If that doesn't help, compare your code to that code. Perhaps you missed some vital part?
Also your getting the debugger here, so... you should use that!
